### ISSUE TITLE
quarkus-cafe-core|application.properties|mongodb connection string

### ISSUE THREAD

**Issue by sachinsgoyal** [jeremyrdavis/quarkus-cafe-demo#5]
![Issue](https://user-images.githubusercontent.com/8142932/87164303-4d5b3d80-c2d1-11ea-8fe4-5923788c1030.PNG)

Hi Sir ,

I am a new to Quarkus, Any specific reason for adding the DB name as its not working in my case but when I removed its working as expected.

%dev.quarkus.mongodb.connection-string = mongodb://cafe-user:redhat-20@sachin-redvm2:27017----------Working
%dev.quarkus.mongodb.connection-string = mongodb://cafe-user:redhat-20@sachin-redvm2:27017/cafedb---Not Working

**Comment by jeremyrdavis** [comment]
Check out the "support" folder.  There is a MongoDB initialization script that creates the "cafedb" database.  You will need to create the database with that name for it to work.  Let me know if you have any issues after trying that.  Thanks for your interest!
